### ISSUE TITLE
Using Unmarshal requires ./dhall-lang/Prelude/JSON/Type.dhall to be present

### ISSUE THREAD

**Issue by Trundle** [philandstuff/dhall-golang#57]
With the JSON decoding introduced in 5b21c3ad53d7d2bac4abbca72c30c9f06a4d3869, dhall-golang now requires `./dhall-lang/Prelude/JSON/Type.dhall` to be present. I guess that's likely not the case, at least not for my program.

I see a few possible options:
* Embed the file using `go generate`: I think this won't work because go get doesn't initialize git submodules
* Use an import instead, with an HTTP fallback. This has the downside that the import machinery is used during initialization, not sure if that is a good idea.

**Comment by mikroskeem** [comment]
I have this issue as well. Right now solved by downgrading to v5.

**Comment by marcelom** [comment]
Also being affected by this. Seems like Go's 1.16 `go:embed` might come in handy for this, but as @Trundle mentioned above, it might not work as well (because go get wont initialize submodules).

Will downgrade to `v5`, but I imagine that this will affect lots of people, since it completely breaks anything that runs on `v6`.

If there are other solutions to this problem, I would highly appreciate. Thanks!

**Comment by pnathan** [comment]
FWIW, this breaks normal `go.mod` usage. Downgrading to v5 solves it. Be good to not use submodules. :-/

**Comment by Gabriel439** [comment]
This can be fixed by hand-writing the equivalent Go AST for `Prelude.JSON.Type` instead of importing it from a file.  I have a PR up that I believe fixes this here: https://github.com/philandstuff/dhall-golang/pull/63
