### ISSUE TITLE
How to define an interface with optional values?

### ISSUE THREAD

**Issue by i-am-the-slime** [philandstuff/dhall-golang#60]
Hi! Thank you very much for building this software for free!

I am having trouble defining the correct `struct` for a `.dhall` with a record with some optional fields.

Do you have an example for this?

**Comment by philandstuff** [comment]
I’m not sure exact what you’re asking. If you mean “what go type should I use to correspond to a dhall record with some optional fields” you have a choice. If you have a dhall field that is, say, `Optional Text`, you could decode it into:

- `*string`: `Some "foo"` will be decoded as a pointer to a new `"foo"`, `None Text` will be decided as `nil`
- `string`: `Some "foo"` will be decoded as `"foo"`, `None Text` will be decoded as the zero value for `string`, which is `""`

The latter is probably more idiomatic Go - in a sense all Go struct fields are optional, and those that are unspecified get given the zero value for the type. But this might be a problem where you need to distinguish between `Some ""` and `None Text` because they both decode to the same value.

hope this helps. I would accept documentation PRs to make this clearer if it wasn’t already.

**Comment by i-am-the-slime** [comment]
Thanks for the quick reply! I think I was asking the wrong question. I'm trying to parse a `dhall` file that looks like this:
```
{ name = "someName"
}
```

Into a struct similar to this:
```
type spagoDhall struct {
	name string
	backend string
}
```

Which makes the `backend` type optional in the sense that it might or might not be there. I suppose that's different from a `Some` vs `None` kind of scenario.

Maybe the only thing I can do in this case is to somehow manually use the parser?

**Comment by philandstuff** [comment]
Hmm. This feels like it’s not the Dhall way of doing things.  I have an implicit design assumption that a config file will have a specific type, and `{name = "foo"}` has a different type from `{name = "foo", backend = "bar"}`. This is kind of what I see the `::` operator as being for - if you prefix the above examples with `MyConfigType::` for an appropriate MyConfigType then they now have the same type. 

However I could be wrong about what is idiomatic Dhall! It might be worth asking the question on the Dhall discourse to get opinions from other implementations.

**Comment by philandstuff** [comment]
(That said, I think that it might Just Work if you try it - Go’s structs are very lenient and have this “everything is optional, and missing values get the default value” thing, so it might just work.)

**Comment by i-am-the-slime** [comment]
Should've specified right away: `panic: Don't know how to decode <nil> into slice` is what I get.
